<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>_02_ControlFlow</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Level1\SelfPractice\" />
    <Folder Include="Level2\SelfPractice\" />
    <Folder Include="Level3\SelfPractice\" />
    <Folder Include="PreparatoryExercises\" />
  </ItemGroup>

</Project>
